apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: bhup0006/sample-app:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"   # Amount of memory guaranteed for the container
            cpu: "250m"      # Amount of CPU guaranteed for the container
          limits:
            memory: "128Mi"  # Maximum amount of memory the container can use
            cpu: "500m"      # Maximum amount of CPU the container can use
