apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-app
  template:
    metadata:
      labels:
        app: gitops-app
    spec:
      containers:
      - name: gitops-app
        image: bhup0006/gitops-app:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"   # Guaranteed memory
            cpu: "250m"      # Guaranteed CPU
          limits:
            memory: "128Mi"  # Max memory
            cpu: "500m"      # Max CPU
